# : PixelBuy for Bungeecord
# : Created by Rubenicos


# Locale configuration
Locale:
  # Available languages: en_US, es_MX
  # If you want to create other language go to "lang" folder and create new file
  Language: 'en_US'
  # Log level for extra messages in console
  # 0 = errors
  # 1 = errors and warnings
  # 2 = errors, warnings and suggestions
  # 3 = errors, warnings, suggestions and debug information
  # Set to -1 to disable all extra messages
  LogLevel: 1


# Server configuration
Server:
  # Available server types:
  # * MAIN : Main server who can handle, SAVE, GET and log donations received from store connection and logger (if set)
  # * SUB : Sub server who only GET data saved by main server (require external database)
  # * GLOBAL: Global server who can handle, SAVE and log donations with global aspects (require a configured logger)
  Type: 'MAIN'
  # Server name identifier
  Name: 'BungeeServer1'
  # Server display name
  DisplayName: '&aSome cool server'


# Server database configuration
Database:
  # Database identifier to SAVE and GET data
  # You can configure databases in database.yml file
  Identifier: 'default'
  # Interval in seconds to SAVE current server data in database
  # Set to 0 to only save when plugin is unloaded
  SaveInterval: 20
  # Interval in seconds to GET other servers data in database
  GetInterval: 20


# Donations configuration
# Donations data represent the total number of donated money and top players
Donations:
  # Maximum number of month donations data will be saved
  # Set -1 to unlimited (not recommended)
  MonthsSize: 12
  # Maximum TOP size
  # Set -1 to disable
  TopSize: 10


# Connection configuration
Connection:
  # List of servers to get data and make logger connections
  # You can set modifiers like "database" and "logger" separated by ; if exists some server
  # with different database or logger
  # Modifiers path '<server identifier>|<modifier1>:<text>;<modifier2>:<text>...'
  List:
    - 'BungeeServer2'
    - 'SomeServerIdentifier'
    - 'BungeeServer3|database:noDefaultDatabase'
    - 'BungeeServer4|database:otherDatabaseIdentifier;logger:redisLogger'


# Plugin commands configuration
# You can reload changes with /pixebuy reload
Commands:
  # Typically /buy command who display shop items
  Buy:
    # Enable or disable this command
    Enable: true
    # Main command
    Cmd: 'buy'
    # Permission to use the command
    # To allow everyone put this in blank
    Permission: 'pixelbuy.command.buy'
    # Other ways to use this command
    Aliases:
      - 'ranks'
      - 'servershop'
